apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-sandopsingress-viewer-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - aasdev.sandtech.io
  resources:
  - sandopsingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aasdev.sandtech.io
  resources:
  - sandopsingresses/status
  verbs:
  - get