---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - frontends.sandtech.io
  resources:
  - frontenddeploys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - frontends.sandtech.io
  resources:
  - frontenddeploys/finalizers
  verbs:
  - update
- apiGroups:
  - frontends.sandtech.io
  resources:
  - frontenddeploys/status
  verbs:
  - get
  - patch
  - update
