# permissions for end users to view sandopsingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sand-ops
    app.kubernetes.io/managed-by: kustomize
  name: sandopsingress-viewer-role
rules:
- apiGroups:
  - aasdev.sandtech.io
  resources:
  - sandopsingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aasdev.sandtech.io
  resources:
  - sandopsingresses/status
  verbs:
  - get
