apiVersion: aasdev.sandtech.io/v1
kind: FrontendDeploy
metadata:
  labels:
    app.kubernetes.io/name: sand-ops
    app.kubernetes.io/managed-by: kustomize
  name: frontenddeploy-sample
  namespace: test-ns
spec:
  imageName: nginx
  port: 80
  isHost: true
  # TODO(user): Add fields here
