apiVersion: frontends.sandtech.io/v1
kind: FrontendDeploy
metadata:
  labels:
    app.kubernetes.io/name: sand-ops
    app.kubernetes.io/managed-by: kustomize
  name: frontenddeploy-sample
  namespace: default
spec:
  imageName: nginx
  port: 80
  # TODO(user): Add fields here
